In [44]:
import pandas as pd

In [45]:
import os

In [46]:
print(os.getcwd())

C:\Users\alinaaleks\Downloads\GitHub\vessel-analytics\src

In [53]:
df = pd.read_csv("../data/raw/counterparts.csv", sep=";")

In [55]:
df.describe(include="all")

,counterpart_id,name,inn,org_type,ctr_type,type,count_inn,name_new,inn_new
count,247.000000,247,247,244,247,247,247.000000,0.0,0.0
unique,NaN,247,242,14,52,23,NaN,NaN,NaN
top,NaN,CSI TARIM ANONIM SIRKETI,"6,16271E+11",ООО,ип,fio_m,NaN,NaN,NaN
freq,NaN,1,3,124,64,67,NaN,NaN,NaN
mean,142.676113,NaN,NaN,NaN,NaN,NaN,11.493927,NaN,NaN
std,83.161174,NaN,NaN,NaN,NaN,NaN,0.864242,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,NaN,11.000000,NaN,NaN
25%,71.500000,NaN,NaN,NaN,NaN,NaN,11.000000,NaN,NaN
50%,141.000000,NaN,NaN,NaN,NaN,NaN,11.000000,NaN,NaN
75%,215.500000,NaN,NaN,NaN,NaN,NaN,11.000000,NaN,NaN
max,287.000000,NaN,NaN,NaN,NaN,NaN,13.000000,NaN,NaN

In [56]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   counterpart_id  247 non-null    int64
 1   name            247 non-null    str
 2   inn             247 non-null    str
 3   org_type        244 non-null    str
 4   ctr_type        247 non-null    str
 5   type            247 non-null    str
 6   count_inn       247 non-null    int64
 7   name_new        0 non-null      float64
 8   inn_new         0 non-null      float64
dtypes: float64(2), int64(2), str(5)
memory usage: 17.5 KB

In [57]:
df.head(5)

,counterpart_id,name,inn,org_type,ctr_type,type,count_inn,name_new,inn_new
0,1,CSI TARIM ANONIM SIRKETI,9909717641,NaN,продажа,foreign,11,NaN,NaN
1,2,CSI Trading FZ-LLC,9550336931,NaN,продажа,foreign,11,NaN,NaN
2,3,Nostrum Artis Limited,2853022980,NaN,продажа,foreign,11,NaN,NaN
3,4,Абдулжелилов Валибек Абдулнасирович ИП,8953844794,ИП,ип,fio_m,11,NaN,NaN
4,5,АВ-ЛОГИСТИК ООО,7666251199,ООО,перевозка,freight,11,NaN,NaN

In [59]:
df["type"].unique()

<StringArray>
[     'foreign',        'fio_m',      'freight',        'fio_f',
         'auto',        'grain',     'terminal',   'facilities',
         'bank', 'port_service',      'consult',       'survey',
           'it',          'ins',          'gov',        'hotel',
      'forward',      'storage',        'media',      'station',
        'clean',      'customs',     'delivery']
Length: 23, dtype: str

### Словари для создания названий компаний

In [60]:
TERMINAL_PREFIX = [
    "Контейнерный", "Грузовой", "Нефтяной", "Угольный",
    "Речной", "Морской", "Балтийский", "Черноморский"
]

TERMINAL_SUFFIX = [
    "Терминал", "Хаб", "Порт", "Комплекс", "Узел"
]

In [61]:
PORT_SERVICE_PREFIX = [
    "Морской", "Порт", "Фрахт", "Навигация", "Балт", "Норд", "Восток",
    "Транс", "Логист", "Си", "Марин", "Шип", "Оушен", "Харбор", "Портовый"
]
PORT_SERVICE_SUFFIX = [
    "Логистик", "Терминал", "Сервис", "Оператор", "Экспресс",
    "Трейд", "Групп", "Шиппинг", "Фрахт", "Контейнер",
    "Альянс", "Навигация", "Солюшнс", "Компания", "Флот"
]

In [62]:
CUSTOMS_PREFIX = [
    "Таможенный", "Внешнеторговый", "Брокерский", "Импорт",
    "Экспорт", "Декларант"
]

CUSTOMS_SUFFIX = [
    "Сервис", "Оператор", "Групп", "Альянс", "Логистик"
]

In [63]:
GRAIN_PREFIX = [
    "Агро", "Зерно", "Колос", "Фермер", "Поле", "Урожай",
    "Агротех", "АгроЛогист", "АгроТрейд", "Сельхоз",
    "Грейн", "Хлеб", "Рост", "Семена", "АгроХим", "МашАгро", "Ферма", "Поле", "Трактор"
]
GRAIN_SUFFIX = [
    "Снаб", "Трейд", "Логистик", "Поставка", "Групп",
    "Сервис", "Альянс", "Экспорт", "Импорт", "Оператор",
    "Центр", "Комплекс", "Агро", "Лаб", "Комплект"
]

In [64]:
STORAGE_PREFIX = [
    "Зерно", "Силос", "Элеватор", "Склад", "АгроЛогист"
]

STORAGE_SUFFIX = [
    "Комплекс", "Терминал", "Центр", "Оператор", "Сервис"
]

In [65]:
FREIGHT_PREFIX = [
    "Авто", "Транс", "Мотор", "Карго", "Кар", "Драйв",
    "Логист", "Экспедит", "Флит", "Роуд", "Трак",
    "Груз", "Доставка", "Вояж"
]
FREIGHT_SUFFIX = [
    "Логистик", "Сервис", "Групп", "Экспресс", "Транс",
    "Лайн", "Оператор", "Флот", "Центр", "Партнер",
    "Солюшнс", "Трейд"
]

In [66]:
FORWARD_PREFIX = [
    "Экспедит", "Логист", "Транс", "Глобал", "Евро",
    "Норд", "Балт", "Си"
]

FORWARD_SUFFIX = [
    "Логистик", "Альянс", "Групп", "Оператор", "Солюшнс"
]

In [67]:
FACILITY_PREFIX = [
    "Офис", "Бизнес", "Сити", "Проф", "Админ",
    "Корп", "Деловой", "Центр", "Управ", "Регион",
    "Консалт", "Сервис", "Альфа", "Аренда", "Комплекс"
]
FACILITY_SUFFIX = [
    "Сервис", "Центр", "Групп", "Лайн", "Оператор",
    "Консалт", "Альянс", "Партнер", "Ресурс", "Солюшнс",
    "Эксперт", "Управление", "Офис", "Бизнес", "Сити", "Корп", "Админ",
    "Деловой"
]

In [68]:
CLEAN_PREFIX = [
    "Клининг", "Чистый", "Сервис", "Офис", "Проф"
]

CLEAN_SUFFIX = [
    "Сервис", "Групп", "Лайн", "Оператор", "Услуги"
]

In [69]:
STATION_PREFIX = [
    "Канц", "Офис", "Бумага", "Документ", "Проф"
]

STATION_SUFFIX = [
    "Снаб", "Сервис", "Трейд", "Поставка", "Центр"
]

In [70]:
CONSULT_PREFIX = [
    "Консалт", "Эксперт", "Аналит", "Бизнес", "Проф"
]

CONSULT_SUFFIX = [
    "Групп", "Сервис", "Альянс", "Партнер", "Решения", "Эксперт"
]

In [71]:
IT_PREFIX = [
    "Софт", "IT", "Диджитал", "Систем", "Тех", "Альфа"
]

IT_SUFFIX = [
    "Системс", "Сервис", "Лаб", "Групп", "Солюшнс", "Платформа"
]

In [72]:
DELIVERY_PREFIX = [
    "Доставка", "Курьер", "Экспресс", "Пост", "Сити"
]

DELIVERY_SUFFIX = [
    "Сервис", "Логистик", "Центр", "Групп", "Оператор"
]

In [73]:
AUTO_PREFIX = [
    "Авто", "Транс", "Мотор", "Кар", "Драйв"
]
AUTO_SUFFIX = [
    "Сервис", "Групп", "Транс",
    "Лайн", "Оператор", "Центр", "Партнер",
    "Солюшнс"
]

In [74]:
FOREIGN_PREFIX = ["Global", "Euro", "Inter", "Nord", "Trade", "World"]
FOREIGN_SUFFIX = ["Group", "Logistics", "Services", "Trading"]

In [75]:
BANK_PREFIX = [
    "Фин", "Банк", "Капитал", "Альфа", "Пром", "Инвест",
    "Траст", "Вектор", "Кредит", "Финанс", "Актив", "Резерв"
]
BANK_SUFFIX = [
    "Банк", "Капитал", "Финанс", "Групп", "Сервис",
    "Альянс", "Инвест", "Лизинг", "Траст", "Операции"
]

In [76]:
GOV_PREFIX = [
    "Федерал", "Регион", "Муницип", "Админ", "Гос",
    "Управ", "Контроль", "Служб", "Центр", "Надзор"
]

GOV_SUFFIX = [
    "Служба", "Департамент", "Управление", "Инспекция",
    "Комитет", "Центр", "Офис", "Агентство"
]

In [77]:
INS_PREFIX = [
    "Страх", "Риск", "Гарант", "Защита", "Проф",
    "Альфа", "Капитал", "Фин", "Мед", "Траст"
]

INS_SUFFIX = [
    "Страхование", "Сервис", "Гарант", "Альянс",
    "Групп", "Партнер", "Оператор"
]

In [78]:
SURVEY_PREFIX = [
    "Сюрвей", "Инспект", "Контроль", "Аудит", "Тех",
    "Марин", "Норд", "Балтик", "Глобал", "Эксперт"
]

SURVEY_SUFFIX = [
    "Сервис", "Групп", "Инспекция", "Контроль",
    "Оценка", "Альянс", "Солюшнс"
]

In [79]:
MEDIA_PREFIX = [
    "Медиа", "Пресс", "МедиаГрупп", "Конференц",
    "Event", "Коммуник", "Паблик", "Реклам"
]

MEDIA_SUFFIX = [
    "Групп", "Сервис", "Альянс", "Продакшн",
    "Медиа", "Солюшнс", "Студия", "Бюро"
]

In [80]:
HOTEL_PREFIX = [
    "Отель", "Плаза", "Гранд", "Роял", "Парк",
    "Сити", "Оушен", "Бриз", "Стар", "Премьер"
]

HOTEL_SUFFIX = [
    "Отель", "Хоспиталити", "Групп", "Резорт",
    "Инн", "Сервис", "Плаза", "Сити"
]

### Создание искусственных ФИО

In [114]:
import random

surname_roots = [
    "Лан", "Вел", "Ром", "Тар", "Зор", "Мир", "Кал", "Нев", "Ор", "Сар",
    "Дал", "Пен", "Кир", "Вар", "Гор", "Лес", "Бор", "Зал", "Рин", "Том",
    "Эр", "Юл", "Акс", "Вен", "Лир", "Сет", "Нор", "Кас", "Мор", "Зен"
]

surname_suffixes = [
    "ев", "ин", "ов", "ар", "ель", "ан", "ор", "ис", "ун",
    "ак", "ир", "ас", "ел", "он", "ур", "ян", "ий", "ес"
]

male_endings = ["ов", "ин", "ский", "ев"]
female_endings = ["ова", "ина", "ская", "ева"]

def generate_surname(gender="m"):
    root = random.choice(surname_roots)
    suffix = random.choice(surname_suffixes)

    if gender == "m":
        return root + suffix + random.choice(male_endings)
    else:
        return root + suffix + random.choice(female_endings)

In [93]:
male_parts_1 = [
    "Але", "Дми", "Сер", "Ан", "Мак", "Ро", "Ил", "Вла",
    "Ни", "Па", "Ге", "Ол", "Кон", "Ти", "Фе", "Ви",
    "Ар", "Ев", "За", "Юр"
]

male_parts_2 = [
    "дар", "мит", "рис", "тон", "вар", "сей", "ким", "дор",
    "лан", "мир", "ней", "рил", "сен", "тор", "вин", "дор",
    "тас", "рон", "вер", "гей"
]

def generate_male_name():
    return random.choice(male_parts_1) + random.choice(male_parts_2)

In [94]:
female_parts_1 = [
    "Ана", "Еле", "Мар", "Оли", "Нат", "Ири", "Све", "Вик",
    "Дар", "Пол", "Ксе", "Люд", "Соф", "Али", "Жан", "Вер",
    "Лео", "Ми", "Те", "Юли"
]

female_parts_2 = [
    "лина", "рия", "нета", "сия", "дина", "сана", "лена",
    "мира", "нара", "тана", "вина", "ета", "ра", "сия", "яна"
]

def generate_female_name():
    return random.choice(female_parts_1) + random.choice(female_parts_2)

In [95]:
patronymic_roots = [
    "Алек", "Ива", "Дми", "Сер", "Ан", "Ник", "Пав", "Мак",
    "Его", "Ром", "Вла", "Кон", "Мих", "Арт", "Вик", "Оле"
]

suffix_m = ["евич", "ович", "ич"]
suffix_f = ["евна", "овна", "ична"]

def generate_patronymic(gender="m"):
    root = random.choice(patronymic_roots)
    return root + random.choice(suffix_m if gender == "m" else suffix_f)

### Генерация

In [101]:
# уникальность
used_names = set()

def ensure_unique(name):
    if name not in used_names:
        used_names.add(name)
        return name

    i = 2
    new_name = f"{name}_{i}"
    while new_name in used_names:
        i += 1
        new_name = f"{name}_{i}"

    used_names.add(new_name)
    return new_name

In [102]:
# случайный шум
import random
import string

def noise():
    return f"{random.choice(string.ascii_uppercase)}{random.randint(10,99)}"

In [105]:
# форматирование - компания
def format_company(name):
    return name.upper()

In [125]:
def format_fio(name, org_type):
    return f"{name} {org_type.upper()}"

In [126]:
def generate_fio_m():
    fio = f"{generate_surname('m')} {generate_male_name()} {generate_patronymic('m')}"
    return fio

In [127]:
def generate_fio_f():
    fio = f"{generate_surname('f')} {generate_female_name()} {generate_patronymic('f')}"
    return fio

In [116]:
def generate_company(prefix_list, suffix_list, org_type):
    name = f"{random.choice(prefix_list)} {random.choice(suffix_list)} {noise()} {org_type}"
    return format_company(name)

In [130]:
def generate_name(row):

    t = row["type"]
    org = row["org_type"]

    # 👤 male fio
    if t == "fio_m":
        base = generate_fio_m()
        return ensure_unique(format_fio(base, org))

    # 👩 female fio
    if t == "fio_f":
        base = generate_fio_f()
        return ensure_unique(format_fio(base, org))

    # 🚛 freight / auto / agro / etc
    if t == "freight":
        return ensure_unique(generate_company(FREIGHT_PREFIX, FREIGHT_SUFFIX, org))

    if t == "auto":
        return ensure_unique(generate_company(AUTO_PREFIX, AUTO_SUFFIX, org))

    if t == "grain":
        return ensure_unique(generate_company(GRAIN_PREFIX, GRAIN_SUFFIX, org))

    if t == "terminal":
        return ensure_unique(generate_company(TERMINAL_PREFIX, TERMINAL_SUFFIX, org))

    if t == "facilities":
        return ensure_unique(generate_company(FACILITY_PREFIX, FACILITY_SUFFIX, org))

    if t == "bank":
        return ensure_unique(generate_company(BANK_PREFIX, BANK_SUFFIX, org))

    if t == "port_service":
        return ensure_unique(generate_company(PORT_SERVICE_PREFIX, PORT_SERVICE_SUFFIX, org))

    if t == "consult":
        return ensure_unique(generate_company(CONSULT_PREFIX, CONSULT_SUFFIX, org))

    if t == "survey":
        return ensure_unique(generate_company(SURVEY_PREFIX, SURVEY_SUFFIX, org))

    if t == "it":
        return ensure_unique(generate_company(IT_PREFIX, IT_SUFFIX, org))

    if t == "ins":
        return ensure_unique(generate_company(INS_PREFIX, INS_SUFFIX, org))

    if t == "gov":
        return ensure_unique(generate_company(GOV_PREFIX, GOV_SUFFIX, org))

    if t == "hotel":
        return ensure_unique(generate_company(HOTEL_PREFIX, HOTEL_SUFFIX, org))

    if t == "forward":
        return ensure_unique(generate_company(FORWARD_PREFIX, FORWARD_SUFFIX, org))

    if t == "storage":
        return ensure_unique(generate_company(STORAGE_PREFIX, STORAGE_SUFFIX, org))

    if t == "media":
        return ensure_unique(generate_company(MEDIA_PREFIX, MEDIA_SUFFIX, org))

    if t == "station":
        return ensure_unique(generate_company(STATION_PREFIX, STATION_SUFFIX, org))

    if t == "clean":
        return ensure_unique(generate_company(CLEAN_PREFIX, CLEAN_SUFFIX, org))

    if t == "customs":
        return ensure_unique(generate_company(CUSTOMS_PREFIX, CUSTOMS_SUFFIX, org))

    if t == "delivery":
        return ensure_unique(generate_company(DELIVERY_PREFIX, DELIVERY_SUFFIX, org))

    if t == "foreign":
        return ensure_unique(generate_company(FOREIGN_PREFIX, FOREIGN_SUFFIX, org))

    return ensure_unique(generate_company(FACILITY_PREFIX, FACILITY_SUFFIX, org))

In [131]:
df["name_new"] = df.apply(generate_name, axis=1)

In [132]:
df.head(15)

,counterpart_id,name,inn,org_type,ctr_type,type,count_inn,name_new,inn_new
0,1,CSI TARIM ANONIM SIRKETI,9909717641,NaN,продажа,foreign,11,EURO SERVICES U18 NAN,NaN
1,2,CSI Trading FZ-LLC,9550336931,NaN,продажа,foreign,11,GLOBAL LOGISTICS R76 NAN,NaN
2,3,Nostrum Artis Limited,2853022980,NaN,продажа,foreign,11,GLOBAL LOGISTICS V22 NAN,NaN
3,4,Абдулжелилов Валибек Абдулнасирович ИП,8953844794,ИП,ип,fio_m,11,Ланевский Пасей Макович ИП,NaN
4,5,АВ-ЛОГИСТИК ООО,7666251199,ООО,перевозка,freight,11,ВОЯЖ ЭКСПРЕСС U89 ООО,NaN
5,6,Авдеенко Дина Владимировна ИП,"6,16602E+11",ИП,ип,fio_f,13,Калийева Дарнета Викична ИП,NaN
6,7,Аведисян Екатерина Олеговна ИП,"6,16271E+11",ИП,ип,fio_m,13,Лирянов Анрил Дмиевич ИП,NaN
7,8,АВТО АПТЕКА ООО,6168121084,ООО,автомобили/ТО,auto,11,МОТОР СЕРВИС M28 ООО,NaN
8,9,АВТОДОР-ПЛАТНЫЕ ДОРОГИ ООО,7710965662,ООО,автомобили/платная дорога,auto,11,МОТОР ЛАЙН L89 ООО,NaN
9,10,АВТОМОЛЛ ООО,6102021755,ООО,основные средства,auto,11,ДРАЙВ ЦЕНТР P91 ООО,NaN
10,11,АВТОСФЕРА ООО,6102073009,ООО,автомобили/ТО,auto,11,МОТОР СЕРВИС W35 ООО,NaN
11,12,АГРОВЕКТОР ООО,6140011839,ООО,перевозка,freight,11,АВТО ЭКСПРЕСС E12 ООО,NaN
12,13,АГРОВОСТОК ООО,5605021340,ООО,закупка,grain,11,МАШАГРО ТРЕЙД T57 ООО,NaN
13,14,АГРОМИР ООО,6165217398,ООО,закупка,grain,11,АГРО ОПЕРАТОР H67 ООО,NaN
14,15,АГРОНОВОЛОГИСТИК ООО,6175637021,ООО,перевозка,freight,11,ТРАНС ГРУПП V87 ООО,NaN

### Новые ИНН

In [144]:
used_inns = set()

def generate_unique_inn(n_digits):
    while True:
        first = str(random.randint(1, 9))
        rest = "".join(str(random.randint(0, 9)) for _ in range(n_digits - 1))
        inn = first + rest

        if inn not in used_inns:
            used_inns.add(inn)
            return inn

In [145]:
df["inn_new"] = df.apply(
    lambda row: generate_unique_inn(int(row["count_inn"])),
    axis=1
)

In [146]:
df.head(15)

,counterpart_id,name,inn,org_type,ctr_type,type,count_inn,name_new,inn_new
0,1,CSI TARIM ANONIM SIRKETI,9909717641,NaN,продажа,foreign,11,EURO SERVICES U18 NAN,51728088251
1,2,CSI Trading FZ-LLC,9550336931,NaN,продажа,foreign,11,GLOBAL LOGISTICS R76 NAN,39435739635
2,3,Nostrum Artis Limited,2853022980,NaN,продажа,foreign,11,GLOBAL LOGISTICS V22 NAN,84268768205
3,4,Абдулжелилов Валибек Абдулнасирович ИП,8953844794,ИП,ип,fio_m,11,Ланевский Пасей Макович ИП,26939133594
4,5,АВ-ЛОГИСТИК ООО,7666251199,ООО,перевозка,freight,11,ВОЯЖ ЭКСПРЕСС U89 ООО,43677064168
5,6,Авдеенко Дина Владимировна ИП,"6,16602E+11",ИП,ип,fio_f,13,Калийева Дарнета Викична ИП,1606145735705
6,7,Аведисян Екатерина Олеговна ИП,"6,16271E+11",ИП,ип,fio_m,13,Лирянов Анрил Дмиевич ИП,1497780126022
7,8,АВТО АПТЕКА ООО,6168121084,ООО,автомобили/ТО,auto,11,МОТОР СЕРВИС M28 ООО,52920631510
8,9,АВТОДОР-ПЛАТНЫЕ ДОРОГИ ООО,7710965662,ООО,автомобили/платная дорога,auto,11,МОТОР ЛАЙН L89 ООО,30191188662
9,10,АВТОМОЛЛ ООО,6102021755,ООО,основные средства,auto,11,ДРАЙВ ЦЕНТР P91 ООО,95313700238
10,11,АВТОСФЕРА ООО,6102073009,ООО,автомобили/ТО,auto,11,МОТОР СЕРВИС W35 ООО,12503856479
11,12,АГРОВЕКТОР ООО,6140011839,ООО,перевозка,freight,11,АВТО ЭКСПРЕСС E12 ООО,46356723307
12,13,АГРОВОСТОК ООО,5605021340,ООО,закупка,grain,11,МАШАГРО ТРЕЙД T57 ООО,50345619814
13,14,АГРОМИР ООО,6165217398,ООО,закупка,grain,11,АГРО ОПЕРАТОР H67 ООО,49149923893
14,15,АГРОНОВОЛОГИСТИК ООО,6175637021,ООО,перевозка,freight,11,ТРАНС ГРУПП V87 ООО,71201593801

In [147]:
df.to_excel("synthetic_data.xlsx", index=False)